version: "3.8"

services:
  exams-mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_USERNAME=ras
      - MYQSL_PASSWORD=rasexams
      - MYSQL_DATABASE=ras_exams
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - exams
    volumes:
      - exams-mysql-data:/var/lib/mysql/data
    ports:
      - 5433:5433
  exams:
    depends_on:
      - exams-mysql
    build: ./exams
    restart: on-failure
    ports:
      - 8001:8001
    networks:
      - exams
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://exams-mysql:5433/ras_exams 
      - DEFAULT_DB_URL=jdbc:mysql://exams-mysql:5433/
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  exams-mysql-data:

networks:
  exams:
    driver: bridge
