version: "3"
services:
  exams-mysql:
    container_name: exams-mysql
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=ras
      - MYSQL_PASSWORD=rasexams
      - MYSQL_DATABASE=ras_exams
      - MYSQL_HOST=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TZ=Europe/Lisbon
    networks:
      - exams
    volumes:
      - mysql-data:/var/lib/mysql
  
  wait-for-db:
    image: atkrad/wait4x
    networks:      
      - exams
    depends_on:
      - exams-mysql
    command: tcp exams-mysql:3306 -t 30s -i 250ms
  
  exams:
    container_name: exams
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    build: ./exams
    restart: on-failure
    ports:
      - 8001:8080
    networks:
      - exams
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://exams-mysql:3306/ras_exams
      - DEFAULT_DB_URL=jdbc:mysql://exams-mysql:3306/
      - TZ=Europe/Lisbon

volumes:
  mysql-data:

networks:
  exams:
    driver: bridge