version: "3.8"

services:
  exams:
    build: ./exams
    ports:
      - 8001:8001
    environment:
      - TZ=Europe/Lisbon
    networks:
      - exams
    depends_on:
      - exams-mysql
  exams-mysql:
    image: mysql:lastest
    restart: unless-stopped
    environment:
      - MYSQL_USERNAME: ras
      - MYQSL_PASSWORD: rasexams
      - MYSQL_DATABASE: ras_exams
    networks:
      - exams
    volumes:
      - exams-mysql-data:/var/lib/mysql/data
    ports:
      - 5433:5433

volumes:
  exams-mysql-data:

networks:
  notifications:
    driver: bridge